version: '3.3'
services:
    nginx:
        ports:
            - '80:80'
        container_name: test
        volumes:
            - '/home/Helloworld/Compose/build/:/usr/share/nginx'
            - '/home/Helloworld/Compose/build/hello.conf:/etc/nginx/conf.d/default.conf'
        image: nginx